definitions:
  models.Book:
    properties:
      author:
        maxLength: 255
        type: string
      book_attrs:
        $ref: '#/definitions/models.BookAttrs'
      book_status:
        type: integer
      created_at:
        type: string
      id:
        type: string
      title:
        maxLength: 255
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    required:
    - author
    - book_attrs
    - book_status
    - id
    - title
    - user_id
    type: object
  models.BookAttrs:
    properties:
      description:
        type: string
      picture:
        type: string
      rating:
        maximum: 10
        minimum: 1
        type: integer
    type: object
  models.Coin:
    properties:
      code:
        maxLength: 10
        minLength: 2
        type: string
      coin_uri:
        $ref: '#/definitions/models.CoinUri'
      created_at:
        type: string
      description:
        maxLength: 255
        type: string
      exchange_id:
        type: string
      id:
        type: string
      image_uri:
        type: string
      is_deleted:
        type: boolean
      name:
        maxLength: 25
        minLength: 2
        type: string
      updated_at:
        type: string
    required:
    - code
    - coin_uri
    - exchange_id
    - id
    - is_deleted
    - name
    type: object
  models.CoinUri:
    properties:
      coin_id:
        type: string
      created_at:
        type: string
      updated_at:
        type: string
      uri:
        type: string
    required:
    - coin_id
    - uri
    type: object
  models.Exchange:
    properties:
      created_at:
        type: string
      description:
        maxLength: 255
        type: string
      id:
        type: string
      is_blocked:
        description: We got blocked?
        type: boolean
      is_deleted:
        description: Is Exchange gone?
        type: boolean
      is_enabled:
        description: Enable Crawling?
        type: boolean
      name:
        maxLength: 25
        type: string
      updated_at:
        type: string
      uri:
        type: string
    required:
    - id
    - name
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        maxLength: 255
        type: string
      id:
        type: string
      password_hash:
        maxLength: 255
        type: string
      updated_at:
        type: string
      user_role:
        maxLength: 25
        type: string
      user_status:
        type: integer
    required:
    - email
    - id
    - password_hash
    - user_role
    - user_status
    type: object
info:
  contact:
    email: p3nj@bumpto.space
    name: API Support
  description: This is an auto-generated API Docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: core API
  version: "1.0"
paths:
  /api/v1/books:
    get:
      consumes:
      - application/json
      description: Get all exists books.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Book'
            type: array
      summary: get all exists books
      tags:
      - Books
  /v1/book:
    delete:
      consumes:
      - application/json
      description: Delete book by given ID.
      parameters:
      - description: Book ID
        in: body
        name: id
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "204":
          description: ok
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: delete book by given ID
      tags:
      - Book
    post:
      consumes:
      - application/json
      description: Create a new book.
      parameters:
      - description: Title
        in: body
        name: title
        required: true
        schema:
          type: string
      - description: Author
        in: body
        name: author
        required: true
        schema:
          type: string
      - description: User ID
        in: body
        name: user_id
        required: true
        schema:
          type: string
      - description: Book attributes
        in: body
        name: book_attrs
        required: true
        schema:
          $ref: '#/definitions/models.BookAttrs'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Book'
      security:
      - ApiKeyAuth: []
      summary: create a new book
      tags:
      - Book
    put:
      consumes:
      - application/json
      description: Update book.
      parameters:
      - description: Book ID
        in: body
        name: id
        required: true
        schema:
          type: string
      - description: Title
        in: body
        name: title
        required: true
        schema:
          type: string
      - description: Author
        in: body
        name: author
        required: true
        schema:
          type: string
      - description: User ID
        in: body
        name: user_id
        required: true
        schema:
          type: string
      - description: Book status
        in: body
        name: book_status
        required: true
        schema:
          type: integer
      - description: Book attributes
        in: body
        name: book_attrs
        required: true
        schema:
          $ref: '#/definitions/models.BookAttrs'
      produces:
      - application/json
      responses:
        "202":
          description: ok
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: update book
      tags:
      - Book
  /v1/book/{id}:
    get:
      consumes:
      - application/json
      description: Get book by given ID.
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Book'
      summary: get book by given ID
      tags:
      - Book
  /v1/coin:
    delete:
      consumes:
      - application/json
      description: Delete coin by given ID.
      parameters:
      - description: Coin ID
        in: body
        name: id
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "204":
          description: ok
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: delete coin by given ID
      tags:
      - Coin
    post:
      consumes:
      - application/json
      description: Create a new coin.
      parameters:
      - description: Name
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: Code
        in: body
        name: code
        required: true
        schema:
          type: string
      - description: Exchange ID
        in: body
        name: exchange_id
        required: true
        schema:
          type: string
      - description: Coin Uri
        in: body
        name: coin_uri
        required: true
        schema:
          $ref: '#/definitions/models.CoinUri'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Coin'
      security:
      - ApiKeyAuth: []
      summary: create a new coin
      tags:
      - Coin
    put:
      consumes:
      - application/json
      description: Update coin.
      parameters:
      - description: Coin ID
        in: body
        name: id
        required: true
        schema:
          type: string
      - description: Name
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: Code
        in: body
        name: code
        required: true
        schema:
          type: string
      - description: Description
        in: body
        name: description
        required: true
        schema:
          type: string
      - description: Exchange ID
        in: body
        name: exchange_id
        required: true
        schema:
          type: string
      - description: Coin Uri
        in: body
        name: coin_uri
        required: true
        schema:
          $ref: '#/definitions/models.CoinUri'
      produces:
      - application/json
      responses:
        "202":
          description: ok
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: update coin
      tags:
      - Coin
  /v1/coin/{id}:
    get:
      consumes:
      - application/json
      description: Get coin by given ID.
      parameters:
      - description: Coin ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Coin'
      summary: get coin by given ID
      tags:
      - Coin
  /v1/coins:
    get:
      consumes:
      - application/json
      description: Get all exists coins.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Coin'
            type: array
      summary: get all exists coins
      tags:
      - Coins
  /v1/exchange:
    delete:
      consumes:
      - application/json
      description: Delete Exchange by given ID.
      parameters:
      - description: Exchange ID
        in: body
        name: id
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "204":
          description: ok
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: delete exchange by given ID
      tags:
      - Exchange
    post:
      consumes:
      - application/json
      description: Create a new exchange.
      parameters:
      - description: Name
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: Description
        in: body
        name: description
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Exchange'
      security:
      - ApiKeyAuth: []
      summary: create a new exchange
      tags:
      - Exchange
    put:
      consumes:
      - application/json
      description: Update exchange.
      parameters:
      - description: Exchange ID
        in: body
        name: id
        required: true
        schema:
          type: string
      - description: Name
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: Description
        in: body
        name: description
        required: true
        schema:
          type: string
      - description: Uri
        in: body
        name: uri
        required: true
        schema:
          type: string
      - description: Is Enabled
        in: body
        name: is_enabled
        required: true
        schema:
          type: boolean
      - description: Is Blocked
        in: body
        name: is_blocked
        required: true
        schema:
          type: boolean
      produces:
      - application/json
      responses:
        "202":
          description: ok
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: update exchange
      tags:
      - Exchange
  /v1/exchange/{id}:
    get:
      consumes:
      - application/json
      description: Get exchange by given ID.
      parameters:
      - description: Exchange ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Exchange'
      summary: get exchange by given ID
      tags:
      - Exchange
  /v1/exchanges:
    get:
      consumes:
      - application/json
      description: Get all exists exchanges.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Exchange'
            type: array
      summary: get all exists exchanges
      tags:
      - Exchanges
  /v1/token/renew:
    post:
      consumes:
      - application/json
      description: Renew access and refresh tokens.
      parameters:
      - description: Refresh token
        in: body
        name: refresh_token
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: renew access and refresh tokens
      tags:
      - Token
  /v1/user/sign/in:
    post:
      consumes:
      - application/json
      description: Auth user and return access and refresh token.
      parameters:
      - description: User Email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: User Password
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: auth user and return access and refresh token
      tags:
      - User
  /v1/user/sign/out:
    post:
      consumes:
      - application/json
      description: De-authorize user and delete refresh token from Redis.
      produces:
      - application/json
      responses:
        "204":
          description: ok
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: de-authorize user and delete refresh token from Redis
      tags:
      - User
  /v1/user/sign/up:
    post:
      consumes:
      - application/json
      description: Create a new user.
      parameters:
      - description: Email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: User role
        in: body
        name: user_role
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: create a new user
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
